# Docker Compose override for development
services:
  app:
    volumes:
      # Mount the entire app directory for development
      - ./app:/app/app
    environment:
      - ENVIRONMENT=development
      - LOG_LEVEL=debug
    command: ["python", "-m", "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
